// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPTTableDesignSample.Context;

#nullable disable

namespace TPTTableDesignSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240628174541_initDatabase")]
    partial class initDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPTTableDesignSample.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parties", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TPTTableDesignSample.Models.Customer", b =>
                {
                    b.HasBaseType("TPTTableDesignSample.Models.Party");

                    b.Property<string>("CustomerSpecificProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("TPTTableDesignSample.Models.Supplier", b =>
                {
                    b.HasBaseType("TPTTableDesignSample.Models.Party");

                    b.Property<string>("SupplierSpecificProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("TPTTableDesignSample.Models.Customer", b =>
                {
                    b.HasOne("TPTTableDesignSample.Models.Party", null)
                        .WithOne()
                        .HasForeignKey("TPTTableDesignSample.Models.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPTTableDesignSample.Models.Supplier", b =>
                {
                    b.HasOne("TPTTableDesignSample.Models.Party", null)
                        .WithOne()
                        .HasForeignKey("TPTTableDesignSample.Models.Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
